# recipe_config.yml

recipes:
  enchanted_potato:
    result: POTATO
    amount: 1
    shape:
      - "DDD"
      - "DAD"
      - "DDD"
    ingredients:
      D: DIAMOND_BLOCK
      A: POTATO
    effects:
      - type: REGENERATION
        duration: 200
        amplifier: 1

  enchanted_carrot:
    result: GOLDEN_CARROT
    amount: 1
    shape:
      - "CCC"
      - "CIC"
      - "CCC"
    ingredients:
      C: CARROT
      I: GOLD_INGOT
    effects:
      - type: SPEED
        duration: 300
        amplifier: 2
